add key checking, remove balance checking
Arcucy/ArcLight pull request #249
Opened 2021-01-10 13:38 UTC by LemonNekoGH

Signed-off-by: LemonNeko <chheese048@gmail.com>
- 修复错误的key无法处理的问题：提前检查是否是ar的key
- 修复没有余额无法登陆的问题：直接移除余额检查

2021-01-10 13:46 UTC, nekomeowww requested changes
已经写好了评论了，APP-NAME 不要提交进来，然后其他的一些改进尽量看看吧w

2021-01-10 13:46 UTC, nekomeowww commented on src/api/arweave.js
> +const APP_NAME = 'arclight-alpha'
这个不要提交进来

2021-01-10 13:46 UTC, nekomeowww commented on src/components/Header.vue
> +          <Search @should-close="closeMobileDialog" class="mobile-search"/>
这行的特别之处是什么呢

2021-01-10 13:46 UTC, nekomeowww commented on src/util/file.js
> +    return content.kty && content.e && content.n && content.d && content.p && content.q && content.dp && content.dq && content.qi
这里应该用 arweave.wallet.jwkToAddress 方法呀，如果这个地方检测 parse 不到信息了就不可用了（因为直接判断 JWK 的属性并不是一种持久化的设计，如果 arweave 更改了 wallet 的结构怎么办？）

2021-01-10 13:46 UTC, nekomeowww commented on src/store/index.js
> +const APP_NAME = 'arclight-alpha'
这个不要提交进来

2021-01-10 13:49 UTC, LemonNekoGH commented on src/components/Header.vue
> +          <Search @should-close="closeMobileDialog" class="mobile-search"/>
这行我没改，可能是ESLint改的，

2021-01-10 13:49 UTC, nekomeowww commented
@KagurazakaIzumi 这边有本地化内容变更，你看看有时间就适配一下

2021-01-10 13:49 UTC, LemonNekoGH commented on src/util/file.js
> +    return content.kty && content.e && content.n && content.d && content.p && content.q && content.dp && content.dq && content.qi
刚刚也发现这个问题

2021-01-12 14:31 UTC, nekomeowww approved these changes

2021-01-12 14:31 UTC, merged