歌曲信息数据的本地缓存 #254 登录框不会消失#274
Arcucy/ArcLight pull request #278
Opened 2021-01-28 05:22 UTC by LemonNekoGH

2021-01-28 09:52 UTC, nekomeowww requested changes
这个 cache 我没看到能先获取数据再处理的过程呀，能不能发一下行号，可能是我没看到。

2021-01-28 09:52 UTC, nekomeowww commented on src/components/Song/GetAudioInfo.vue
> +          // }
处理一下注释

2021-01-28 09:52 UTC, nekomeowww commented on src/pages/Songs/Index.vue
> +        // }
同上

2021-01-28 09:52 UTC, nekomeowww commented on src/pages/User/index.vue
> +        // }
同上

2021-01-28 09:52 UTC, nekomeowww commented on src/pages/Album/_id.vue
> +        // const albumData = JSON.parse(decode.uint8ArrayToString(transaction.data))
处理一下注释

2021-01-28 12:07 UTC, nekomeowww commented on src/api/arweave.js
> +          console.log('get cover timeout, retrying...')
没必要的 console.log 就删掉吧（虽然我也有好多没删

2021-01-28 12:07 UTC, nekomeowww commented on src/api/arweave.js
> +          console.log('get cover timeout, retrying...')
没必要的 console.log 就删掉吧（虽然我也有好多没删

2021-01-28 12:08 UTC, nekomeowww commented on src/api/arweave.js
> +      }
这个 if else 能写成
```Javascript
if (data) do()
else do()
```
的模式么？

2021-01-28 12:15 UTC, nekomeowww requested changes

2021-01-28 12:15 UTC, nekomeowww commented on src/pages/User/index.vue
> +        // }
这个部分好像还在

2021-01-29 02:28 UTC, nekomeowww commented on src/util/cache.js
> +      }
这个 info 要不要加 default 判断一下呀？
万一没操作好传进来的并不是 info 的怎么办

2021-01-29 03:16 UTC, LemonNekoGH commented on src/util/cache.js
> +      }
不用吧，因为如果不是info应该就直接报错了

2021-01-29 08:42 UTC, nekomeowww approved these changes

2021-01-29 08:55 UTC, merged